# Generated by Django 3.2.13 on 2022-07-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='Department_name',
        ),
    ]
